import React from "react";

const PrivacyPolicy = () => (
  <div style={{ background: '#f5f5f5', padding: 24, borderRadius: 8, maxWidth: 900, margin: '32px auto' }}>
    <h1 style={{ textAlign: 'center' }}>Chính Sách Bảo Mật Dinner Chill</h1>
    <p style={{ textAlign: 'center', fontStyle: 'italic' }}>
      Cập nhật và có hiệu lực: 05 tháng 06 năm 2024
    </p>
    <div style={{ textAlign: 'left' }}>
      <p>Chính sách bảo mật của Dinner Chill ("Chính sách") để mô tả cách nền tảng Dinner Chill, Công ty cổ phần Dinner Chill (gọi chung là "Dinner Chill", "Chúng tôi" hoặc "của chúng tôi") thu thập, sử dụng, xử lý và chia sẻ thông tin cá nhân từ khách hàng hiện tại hoặc tương lai của nhà hàng, nhà cung cấp dịch vụ và đối tác. Chính sách này áp dụng cho khách hàng hiện tại và tương lai của nhà hàng, nhà cung cấp dịch vụ và đối tác truy cập và/hoặc sử dụng (gọi là "bạn") các trang web, ứng dụng, tài khoản mạng xã hội, các dịch vụ trực tuyến khác của Dinner Chill hoặc tương tác với chúng tôi trực tuyến hoặc ngoại tuyến (gọi chung là "Dịch vụ" của chúng tôi). Đối với các loại thông tin hoặc quá trình xử lý cụ thể, chúng tôi có thể cung cấp cho bạn các lựa chọn hoặc yêu cầu bạn đồng ý bổ sung liên quan đến thông tin chúng tôi thu thập và cách chúng tôi có thể xử lý thông tin đó. Xin lưu ý rằng việc bạn sử dụng Dịch vụ của chúng tôi cũng phải tuân theo: Điều khoản sử dụng, Quy chế Hoạt động, Điều khoản với Đối tác của Dinner Chill hoặc thỏa thuận khác mà bạn có thể có với chúng tôi.</p>
      <p><b>Những chủ đề chính của Chính sách này:</b></p>
      <ul>
        <li>Thông tin chúng tôi thu thập và sử dụng</li>
        <li>Chúng tôi sử dụng thông tin của bạn như thế nào</li>
        <li>Chúng tôi chia sẻ thông tin của bạn như thế nào</li>
        <li>Cách chúng tôi lưu trữ và bảo vệ thông tin của bạn</li>
        <li>Sự lựa chọn và quyền của bạn</li>
        <li>Chuyển giao thông tin Quốc tế</li>
        <li>Liên kết đến các trang web khác</li>
        <li>Về trẻ em</li>
        <li>Những thay đổi đối với Chính sách này</li>
        <li>Làm thế nào để liên hệ với chúng tôi</li>
      </ul>
      <h3>I. THÔNG TIN CHÚNG TÔI THU THẬP VÀ SỬ DỤNG</h3>
      <p>Khi bạn sử dụng hoặc truy cập Dịch vụ của chúng tôi, chúng tôi thu thập thông tin trực tiếp từ bạn (ví dụ: khi bạn thực hiện các lựa chọn trên nền tảng của chúng tôi). Chúng tôi cũng có thể tạo thông tin về bạn (ví dụ: thông tin về thiết bị của bạn khi bạn sử dụng ứng dụng di động của chúng tôi). Trong một số trường hợp, chúng tôi cũng thu thập thông tin cá nhân từ bên thứ ba (ví dụ: nhà hàng, đối tác kinh doanh, hoặc các bên thứ ba khác). Chúng tôi cũng có thể thu thập thông tin thông qua lịch sử truy cập, các tương tác bạn để lại khi truy cập và sử dụng Dịch vụ của chúng tôi, ví dụ: Đã xem, Yêu thích, Chia sẻ, ảnh hoặc thông tin trực quan như ảnh hồ sơ của bạn, thông tin thương mại như lịch sử giao dịch,...</p>
      <p><b>"Thông tin cá nhân"</b> là dữ liệu nhận dạng, liên quan đến, mô tả, có thể được sử dụng để liên hệ hoặc có thể được liên kết hợp lý trực tiếp hoặc gián tiếp với bạn. Đối với mục đích của Chính sách này, không có sự phân biệt có ý nghĩa giữa các thuật ngữ "thông tin cá nhân" và "dữ liệu cá nhân".</p>
      <p><b>Thông tin cá nhân chúng tôi thu thập trực tiếp từ bạn.</b> Một số phần nhất định trên Trang web của chúng tôi có thể yêu cầu bạn cung cấp thông tin cá nhân. Ví dụ, nếu bạn cung cấp thông tin liên lạc của mình để đăng ký tài khoản với chúng tôi, đăng ký nhận thông tin tiếp thị (như bản tin của chúng tôi) hoặc cho phép chúng tôi liên hệ với bạn. Nếu bạn liên hệ với chúng tôi để tìm hiểu thêm về Dịch vụ Dinner Chill, chúng tôi sẽ thu thập thông tin cá nhân về bạn để chúng tôi có thể đáp ứng yêu cầu của bạn.</p>
      <p>Chúng tôi thu thập những thông tin cá nhân sau đây từ bạn, tùy thuộc vào sản phẩm và tính năng bạn sử dụng:</p>
      <ul>
        <li>Thông tin cá nhân Tên, thông tin liên lạc (ví dụ: địa chỉ email và số điện thoại) hoặc địa chỉ của bạn.</li>
        <li>Thông tin liên hệ của nhà hàng và doanh nghiệp Tên của tổ chức hoặc thực thể mà bạn đại diện, địa chỉ email, địa chỉ bưu chính hoặc số điện thoại.</li>
        <li>Nội dung nhà hàng Hồ sơ Gian hàng về nhà hàng, ảnh nhà hàng, thực đơn và các tài liệu tương tự khác mà bạn cung cấp cho chúng tôi.</li>
        <li>Thông tin tài khoản Cài đặt tài khoản hoặc mật khẩu của bạn.</li>
        <li>Các thông tin tùy chọn trên Dinner Chill của bạn, như cài đặt trong sản phẩm ưa thích hoặc cấu hình dành riêng cho tài khoản.</li>
        <li>Thông tin mạng xã hội Liên kết đến tài khoản mạng xã hội của nhà hàng bạn.</li>
        <li>Thông tin liên lạc bạn gửi cho chúng tôi Các yêu cầu hỗ trợ khách hàng hoặc các yêu cầu khác mà bạn thực hiện thông qua Dịch vụ của chúng tôi.</li>
        <li>Thông tin khác mà bạn có thể cung cấp Thông tin bạn cung cấp về bản thân hoặc người khác thông qua Dịch vụ của chúng tôi hoặc thông tin bạn cung cấp cho chúng tôi quyền truy cập thông qua nền tảng của bên thứ ba.</li>
      </ul>
      <p>Bạn có thể chọn không cung cấp một số thông tin cá nhân được mô tả ở trên. Tuy nhiên, xin lưu ý rằng Dịch vụ của chúng tôi có thể yêu cầu một số thông tin cá nhân để hoạt động, vì vậy nếu bạn chọn không cung cấp thông tin cá nhân cần thiết để hoạt động và cung cấp cho bạn một tính năng cụ thể, bạn có thể không sử dụng được tính năng đó.</p>
      <p><b>Thông tin cá nhân nhạy cảm.</b>  Chúng tôi không chủ động thu thập thông tin cá nhân nhạy cảm, nhưng trong quá trình giao tiếp với chúng tôi, bạn có thể tự do lựa chọn chia sẻ thông tin có thể được coi là nhạy cảm. Trong trường hợp bạn chia sẻ thông tin đó với chúng tôi, chúng tôi không sử dụng thông tin này cho mục đích tiếp thị hoặc quảng cáo sản phẩm cho bạn. Ngoài ra, một số tính năng nhất định của Dịch vụ của chúng tôi có thể nhắc thiết bị hoặc trình duyệt của bạn yêu cầu truy cập thông tin định vị địa lý chính xác của bạn, có thể được coi là thông tin cá nhân nhạy cảm. Chúng tôi không xử lý định vị địa lý chính xác nếu bạn không cấp quyền thông qua thiết bị hoặc trình duyệt của mình. Thông tin cá nhân nhạy cảm mà bạn tự nguyện gửi sẽ được xử lý trên cơ sở sự đồng ý của bạn, bạn có thể thu hồi bất kỳ lúc nào bằng cách liên hệ với chúng tôi theo thông tin chi tiết được nêu trong phần Cách liên hệ với chúng tôi  bên dưới.</p>
      <p><b>Thông tin cá nhân do chúng tôi tạo ra.</b> Khi bạn truy cập Dịch vụ của chúng tôi, chúng tôi tạo ra một số thông tin cá nhân nhất định về bạn, bao gồm thông qua việc thu thập dữ liệu tự động và thông qua suy luận dựa trên thông tin chúng tôi thu thập về bạn và hoạt động của bạn. Chúng tôi có thể tự động thu thập thông tin về các tương tác của bạn với Dịch vụ hoặc thông tin liên lạc mà bạn nhận được (chẳng hạn như email, tin push ứng dụng,...)</p>
      <p>Chúng tôi tạo ra các loại thông tin cá nhân sau đây về bạn:</p>
      <ul>
        <li>Thông tin thiết bị. Loại thiết bị (ví dụ: thiết bị di động, máy tính hoặc máy tính bảng), thông tin về phần cứng và phần mềm, cấu hình thiết bị, hệ điều hành thiết bị, trình duyệt, mã định danh thiết bị (ví dụ: địa chỉ IP, số IMEI, địa chỉ MAC) và quốc gia xuất xứ, khu vực và cài đặt ngôn ngữ.</li>
        <li>Thông tin sử dụng và hiệu suất. Chúng tôi cũng tự động thu thập thông tin cá nhân về việc bạn sử dụng Dịch vụ, bao gồm thông tin về các tìm kiếm hoặc tương tác của bạn với các tính năng của Dịch vụ của chúng tôi; các trang hoặc trang đã truy cập; đường dẫn đặt chỗ; thời gian truy cập.</li>
        <li>Thông tin vị trí. Nếu bạn truy cập Dịch vụ trực tuyến của chúng tôi, chúng tôi sẽ tự động thu thập thông tin vị trí chung về bạn (như thành phố, khu phố, địa danh,...) hoặc, với sự đồng ý của bạn, dữ liệu vị trí địa lý chính xác từ thiết bị di động của bạn khi ứng dụng đang chạy và khi ứng dụng không chạy, tùy thuộc vào lựa chọn bạn đưa ra khi bạn được yêu cầu đồng ý với việc chúng tôi thu thập thông tin vị trí.</li>
        <li>Suy luận về bạn. Chúng tôi kết hợp thông tin chúng tôi thu thập, tạo ra hoặc có được theo cách khác để rút ra suy luận về sở thích và mối quan tâm của bạn nhằm cung cấp và cá nhân hóa Dịch vụ của chúng tôi và điều chỉnh các ưu đãi mà chúng tôi và các đối tác của chúng tôi cung cấp cho bạn.</li>
      </ul>
      <p>Chúng tôi có thể sử dụng và lưu trữ thông tin này để cung cấp và cải thiện các tính năng của Dịch vụ của chúng tôi, ví dụ, để điều chỉnh Dịch vụ của chúng tôi theo cách dựa trên nhu cầu để tạo điều kiện thuận lợi hơn cho các yêu cầu của bạn và cung cấp cho bạn nội dung và tính năng phù hợp hơn. Vui lòng xem phần Quyền và Lựa chọn của bạn  bên dưới để biết thêm thông tin về cách điều chỉnh tùy chọn của bạn, bao gồm cả những tùy chọn liên quan đến thông tin vị trí.</p>
      <p><b>Thông tin cá nhân chúng tôi thu thập từ bên thứ ba.</b> Chúng tôi cũng có thể nhận được một số loại thông tin cá nhân từ bên thứ ba, chẳng hạn như các trang web, ứng dụng, mạng xã hội và dịch vụ của bên thứ ba (có thể bao gồm các nguồn công khai; mỗi nguồn này là một "nền tảng của bên thứ ba"). Nếu bạn là khách hàng hiện tại của nhà hàng trên Dinner Chill, chúng tôi sẽ kết hợp thông tin này với thông tin chúng tôi thu thập thông qua Dịch vụ của mình và sử dụng cũng như chia sẻ thông tin đó cho các mục đích được mô tả bên dưới. Các loại thông tin cá nhân chúng tôi có thể thu thập từ bên thứ ba bao gồm:</p>
      <ul>
        <li>Tên của bạn</li>
        <li>Địa chỉ email, số điện thoại hoặc thông tin liên lạc khác</li>
        <li>Dữ liệu phương tiện truyền thông xã hội, nếu bạn kết nối với Dịch vụ của chúng tôi bằng nền tảng phương tiện truyền thông xã hội của bên thứ ba hoặc nếu bất kỳ dữ liệu phương tiện truyền thông xã hội nào của bạn có sẵn cho công chúng, chúng tôi có thể nhận thông tin từ nền tảng phương tiện truyền thông xã hội của bên thứ ba đó hoặc dịch vụ của bên thứ ba về những tương tác đó và hồ sơ của bạn</li>
        <li>Chi tiết về duyệt, sử dụng và quảng cáo, bao gồm cách bạn sử dụng Dịch vụ của chúng tôi và/hoặc các trang web, ứng dụng và dịch vụ của bên thứ ba, cũng như thông tin liên quan đến tương tác của bạn với tài liệu quảng cáo và tiếp thị của chúng tôi.</li>
      </ul>
      <p>Bên thứ ba cũng có thể thu thập, sử dụng và chia sẻ thông tin về bạn (chẳng hạn như các nền tảng độc lập mà bạn chọn sử dụng liên quan đến Dịch vụ của chúng tôi, ví dụ: bộ xử lý thanh toán). Chính sách này không bao gồm các dịch vụ của bên thứ ba đó hoặc việc họ sử dụng thông tin cá nhân và chúng tôi không chịu trách nhiệm về các hoạt động bảo mật của họ. Để biết thêm thông tin về thông tin chúng tôi chia sẻ với bên thứ ba và người nhận thông tin đó, vui lòng tham khảo phần Cách chúng tôi chia sẻ thông tin của bạn trong Chính sách này.</p>
      <h3>II. CHÚNG TÔI SỬ DỤNG THÔNG TIN CỦA BẠN NHƯ THẾ NÀO</h3>
      <p>Chúng tôi sử dụng thông tin của bạn không có gì khác là để cung cấp Dịch vụ của chúng tôi cho bạn, tùy chỉnh trải nghiệm của bạn, gửi cho bạn thông tin tiếp thị, cải thiện Dịch vụ của chúng tôi, cải thiện dịch vụ khách hàng của chúng tôi và cho các mục đích khác được mô tả bên dưới. Nếu bạn cần được thông báo về các hành động mới của thực khách tại nhà hàng của bạn (chẳng hạn như đặt chỗ và giao dịch mới), chúng tôi sẽ sử dụng thông tin bạn cung cấp để thông báo các sự kiện đó cho bạn. Chúng tôi cũng cung cấp cho bạn khả năng giao tiếp với thực khách, chẳng hạn như thông báo cho họ về những thay đổi đối với đặt chỗ của họ.</p>
      <p>Chúng tôi sử dụng thông tin này (riêng lẻ hoặc kết hợp với thông tin khác mà chúng tôi đã thu thập về bạn) cho các mục đích sau ("Mục đích"):</p>
      <ul>
        <li>Cung cấp Dịch vụ, bao gồm cung cấp cho bạn các dịch vụ, sản phẩm và chức năng được cung cấp thông qua Dịch vụ của chúng tôi theo yêu cầu của bạn.</li>
        <li>Cho các hoạt động nội bộ của chúng tôi. Để quản lý Dịch vụ của chúng tôi và cho các hoạt động nội bộ, bao gồm khắc phục sự cố, phân tích dữ liệu, thử nghiệm, nghiên cứu, mục đích thống kê và khảo sát.</li>
        <li>Để cải thiện Dịch vụ của chúng tôi. Để hiểu cách Dịch vụ của chúng tôi được sử dụng và cải thiện Trang web của chúng tôi để đảm bảo rằng nội dung được trình bày theo cách hiệu quả nhất cho bạn và máy tính của bạn.</li>
        <li>Để giữ cho Dịch vụ của chúng tôi và tài khoản của bạn được an toàn. Để xác thực thông tin tài khoản của bạn và nhận dạng bạn, khi cần thiết để đăng nhập bạn vào Dịch vụ và như một phần trong nỗ lực của chúng tôi nhằm giữ cho Dịch vụ của chúng tôi và tài khoản của bạn được an toàn.</li>
        <li>Để liên lạc với bạn về tài khoản của bạn hoặc việc bạn sử dụng Dịch vụ, sản phẩm và/hoặc tính năng; để trả lời hoặc theo dõi các bình luận và câu hỏi của bạn và để cung cấp cho bạn dịch vụ khách hàng.</li>
        <li>Cung cấp cho bạn các dịch vụ, ưu đãi và tiếp thị có liên quan, bao gồm mục đích quảng cáo và cung cấp nội dung có liên quan hơn, bao gồm trao đổi với bạn về các dịch vụ hoặc sản phẩm do Dinner Chill, các đối tác kinh doanh của chúng tôi cung cấp và các thông tin tiếp thị khác mà chúng tôi tin rằng bạn sẽ quan tâm, theo luật pháp cho phép.</li>
        <li>Để tuân thủ và thực thi các yêu cầu, thỏa thuận và chính sách pháp lý hiện hành, bao gồm các yêu cầu của chính phủ và để xác thực danh tính của bạn khi cần thiết.</li>
        <li>Để phòng ngừa và bảo vệ gian lận. Để bảo vệ, điều tra và ngăn chặn các hoạt động gian lận, trái phép hoặc bất hợp pháp.</li>
        <li>Cho các mục đích khác, nếu được bạn đồng ý và được pháp luật hiện hành cho phép.</li>
      </ul>
      <p>Bạn có quyền lựa chọn về thông tin cá nhân của mình và trong một số trường hợp, bạn có thể có quyền từ chối hoặc phản đối việc chúng tôi sử dụng thông tin cá nhân của bạn cho các Mục đích này. Để biết thêm thông tin hoặc thực hiện các quyền này hoặc các quyền khác (nếu có), hãy xem phần Lựa chọn và Quyền của bạn bên dưới.</p>
      <p>Chúng tôi có thể cung cấp thông tin của bạn cho các chi nhánh hay các Phòng/Ban trong Công ty của chúng tôi. Các chi nhánh của chúng tôi sẽ chỉ sử dụng thông tin của bạn cho các mục đích được mô tả trong Chính sách này.</p>
      <p>Khi chúng tôi xử lý thông tin cá nhân của bạn, chúng tôi dựa vào các cơ sở pháp lý sau:</p>
      <ul>
        <li>Thực hiện hợp đồng mà chúng tôi có với bạn (chẳng hạn như nếu bạn sử dụng Dịch vụ của chúng tôi cho mục đích đặt chỗ nhà hàng hoặc quản lý bàn, chúng tôi sẽ sử dụng thông tin của bạn để thực hiện nghĩa vụ hợp đồng của mình là cung cấp Dịch vụ cho bạn bằng cách chia sẻ thông tin của bạn trên nền tảng của chúng tôi).</li>
        <li>Tuân thủ các nghĩa vụ pháp lý mà chúng tôi phải tuân thủ (chẳng hạn như nghĩa vụ thuế và khi chúng tôi có nghĩa vụ tuân thủ các yêu cầu hợp pháp từ các cơ quan có thẩm quyền như cơ quan thực thi pháp luật).</li>
        <li>Để phục vụ cho lợi ích hợp pháp của chúng tôi (chẳng hạn như tùy chỉnh trải nghiệm của bạn với các Trang web hoặc Dịch vụ của chúng tôi, thực hiện quảng cáo trực tuyến và phát hiện gian lận), với điều kiện là việc xử lý đó không vượt quá quyền và quyền tự do của bạn. Việc xử lý cũng có thể tuân theo các cơ sở pháp lý áp dụng khác để xử lý dữ liệu, đặc biệt là các điều khoản được nêu trong luật pháp địa phương.</li>
      </ul>
      <p>Khi chúng tôi sử dụng thông tin cá nhân để đáp ứng các lợi ích hợp pháp của mình, chúng tôi thực hiện các bước được thiết kế để đảm bảo rằng các quyền của bạn liên quan đến thông tin cá nhân của bạn không bị xâm phạm. Bạn có thể liên hệ với chúng tôi bằng cách sử dụng các chi tiết được nêu trong phần Cách liên hệ với chúng tôi bên dưới để biết thêm thông tin về các bước chúng tôi thực hiện để đảm bảo các quyền này không bị xâm phạm. Bạn cũng có quyền phản đối việc xử lý như được mô tả trong phần Lựa chọn và Quyền của bạn bên dưới.</p>
      <p><b>Căn cứ bổ sung để xử lý</b></p>
      <ul>
        <li>Sự đồng ý. Trong phạm vi mà căn cứ pháp lý được mô tả ở trên không áp dụng cho việc chúng tôi xử lý thông tin cá nhân của bạn, chúng tôi sẽ tìm kiếm sự đồng ý của bạn cho các mục đích cụ thể đó theo luật hiện hành (chẳng hạn như gửi tin nhắn tiếp thị trực tiếp bằng phương tiện điện tử, như email, mà không có ngoại lệ về yêu cầu phải có được sự đồng ý).</li>
        <li>Thông tin tổng hợp. Chúng tôi tổng hợp thông tin cá nhân được thu thập trực tiếp từ bạn, thông tin do chúng tôi tạo ra về bạn và thông tin thu được từ bên thứ ba (với sự đồng ý của bạn, nếu cần) với thông tin cá nhân được thu thập về các nhà hàng tiềm năng hoặc hiện tại khác để tạo ra số liệu thống kê chung không thể liên kết với bạn hoặc bất kỳ nhà hàng hoặc người dùng nhà hàng cụ thể nào khác. Thông tin đã được tổng hợp và xóa nhận dạng không còn được coi là "thông tin cá nhân" và sau đó có thể được sử dụng cho bất kỳ mục đích nào theo luật hiện hành.</li>
        <li>Thông tin ẩn danh.  Chúng tôi có thể xử lý thông tin không thể liên kết với bạn hoặc bất kỳ nhà hàng hoặc người dùng nhà hàng cụ thể nào khác bằng bất kỳ phương tiện nào có sẵn cho chúng tôi, vì thông tin đó được thu thập ẩn danh hoặc sau đó đã được ẩn danh. Thông tin ẩn danh hoặc đã được ẩn danh không còn được coi là "thông tin cá nhân" và sau đó có thể được sử dụng cho bất kỳ mục đích nào theo luật hiện hành.</li>
      </ul>
      <h3>III. CÁCH CHÚNG TÔI CHIA SẺ THÔNG TIN CỦA BẠN</h3>
      <p>Chúng tôi tiết lộ thông tin cá nhân mà chúng tôi thu thập (hoặc tạo ra hoặc thu được) như sau:</p>
      <ul>
        <li>Với các chi nhánh nhà hàng của bạn.  Chúng tôi chia sẻ thông tin của bạn với các chi nhánh nhà hàng của bạn cho mục đích riêng của nhà hàng hoặc nhóm nhà hàng, có thể bao gồm mục đích tiếp thị hoặc quảng cáo.</li>
        <li>Với các đối tác kinh doanh khác.  Chúng tôi chia sẻ thông tin với các đối tác kinh doanh bên thứ ba khác cho mục đích tiếp thị của riêng họ, bao gồm chia sẻ với các nhà quảng cáo trực tuyến hoặc các công ty công nghệ quảng cáo (công nghệ quảng cáo) để cung cấp cho bạn quảng cáo được nhắm mục tiêu và truyền thông tiếp thị, khi được pháp luật cho phép (xem bên dưới để biết thêm chi tiết về Chia sẻ với các Đối tác kinh doanh của chúng tôi).</li>
        <li>Với các dịch vụ mạng xã hội.  Chúng tôi chia sẻ (hoặc tạo điều kiện cho bạn chia sẻ) thông tin của bạn với các dịch vụ mạng xã hội khi bạn sử dụng Dịch vụ của chúng tôi để kết nối và chia sẻ thông tin của bạn một cách công khai hoặc khi bạn sử dụng Dịch vụ của chúng tôi để kết nối với chúng tôi trên, chia sẻ trên hoặc sử dụng các nền tảng và dịch vụ mạng xã hội của bên thứ ba (xem bên dưới để biết thêm chi tiết về Chia sẻ với Dịch vụ mạng xã hội).</li>
        <li>Các dịch vụ hoặc ứng dụng của bên thứ ba mà bạn sử dụng để đăng nhập vào tài khoản của mình. Nếu bạn hoặc người dùng nhà hàng của bạn sử dụng dịch vụ hoặc ứng dụng của bên thứ ba (ví dụ: Facebook) để đăng nhập vào tài khoản Dinner Chill của bạn, chúng tôi sẽ chia sẻ một số thông tin cá nhân nhất định với bên thứ ba đó, chẳng hạn như tên và địa chỉ email của bạn.</li>
        <li>Với các nhà cung cấp dịch vụ khác.  Chúng tôi chia sẻ thông tin với các nhà cung cấp bên thứ ba, cố vấn và các nhà cung cấp dịch vụ bên thứ ba thực hiện các dịch vụ hoặc chức năng thay mặt chúng tôi (ví dụ: lưu trữ hoặc vận hành Dịch vụ của chúng tôi, thu thập dữ liệu, báo cáo, đo lường phản hồi quảng cáo, phân tích trang web, phân tích dữ liệu, gửi thông điệp tiếp thị và quảng cáo, và cung cấp dịch vụ phát hiện gian lận). Chúng tôi không cho phép các bên thứ ba này sử dụng hoặc tiết lộ thông tin của bạn cho các mục đích khác ngoài mục đích mà thông tin đã được cung cấp. Chúng tôi yêu cầu các bên thứ ba này duy trì và triển khai các biện pháp bảo mật để bảo vệ thông tin của bạn khỏi việc truy cập hoặc xử lý trái phép.</li>
      </ul>
      <h3>IV. CHÚNG TÔI LƯU TRỮ VÀ BẢO VỆ THÔNG TIN CỦA BẠN NHƯ THẾ NÀO</h3>
      <ul>
        <li>Chúng tôi duy trì các biện pháp bảo mật kỹ thuật, hành chính và vật lý hợp lý về mặt thương mại được thiết kế để bảo vệ thông tin của bạn khỏi bị mất mát, sử dụng sai mục đích, truy cập trái phép, tiết lộ, thay đổi và phá hủy.</li>
        <li>Bảo vệ an ninh. Chúng tôi sử dụng các biện pháp bảo mật kỹ thuật và tổ chức được thiết kế để bảo vệ thông tin cá nhân mà chúng tôi xử lý về khách truy cập Dịch vụ của chúng tôi khỏi việc truy cập, tiết lộ, thay đổi và phá hủy trái phép. Tuy nhiên, xin lưu ý rằng không có đường truyền Internet nào có thể được đảm bảo an toàn 100%, vì vậy chúng tôi khuyến khích bạn cẩn thận khi tiết lộ thông tin cá nhân trực tuyến và sử dụng các công cụ có sẵn, chẳng hạn như tường lửa Internet, email an toàn và các công nghệ tương tự để bảo vệ bản thân trực tuyến. Ngoại trừ phạm vi trách nhiệm pháp lý không thể bị loại trừ hoặc giới hạn do luật hiện hành, chúng tôi không chịu bất kỳ trách nhiệm pháp lý hoặc trách nhiệm nào đối với việc tiết lộ thông tin của bạn do lỗi truyền tải, truy cập trái phép của bên thứ ba hoặc các nguyên nhân khác nằm ngoài tầm kiểm soát của chúng tôi.</li>
        <li>Bạn đóng vai trò quan trọng trong việc giữ thông tin của bạn được an toàn. Bạn hoặc người dùng nhà hàng của bạn không được chia sẻ tên người dùng, mật khẩu hoặc thông tin bảo mật khác cho tài khoản Dinner Chill của bạn với bất kỳ ai. Nếu chúng tôi nhận được hướng dẫn sử dụng tên người dùng và mật khẩu của bạn, chúng tôi sẽ cho rằng bạn đã ủy quyền cho các hướng dẫn đó. Nếu bạn có lý do để tin rằng tương tác của bạn với chúng tôi không còn an toàn nữa (ví dụ: nếu bạn cảm thấy rằng tính bảo mật của bất kỳ tài khoản nào bạn có với chúng tôi đã bị xâm phạm), vui lòng liên hệ với chúng tôi ngay lập tức theo thông tin chi tiết trong phần Cách liên hệ với chúng tôi bên dưới.</li>
        <li>Lưu giữ. Chúng tôi có thể lưu giữ thông tin cá nhân của bạn hoặc người dùng nhà hàng của bạn miễn là tài khoản của bạn vẫn hoạt động và phù hợp với bất kỳ thỏa thuận nào bạn có thể có với chúng tôi về Dịch vụ của chúng tôi. Sau khi tài khoản của bạn không hoạt động hoặc sau khi chấm dứt bất kỳ thỏa thuận nào chúng tôi có thể có với bạn, chúng tôi có thể lưu giữ thông tin liên hệ kinh doanh chung trong tối đa bảy năm. Chúng tôi cũng có thể lưu giữ thông tin cá nhân của bạn khi cần thiết để:</li>
        <ul>
          <li>Duy trì nhật ký và hồ sơ kinh doanh cho mục đích phân tích, bảo mật và/hoặc kiểm toán</li>
          <li>Tuân thủ các yêu cầu lưu giữ hồ sơ theo luật định</li>
          <li>Giải quyết mọi khiếu nại liên quan đến Dịch vụ; và</li>
          <li>Tuân thủ các nghĩa vụ pháp lý của chúng tôi, bảo vệ hoặc bảo vệ quyền của chúng tôi, giải quyết tranh chấp và thực thi hợp đồng của chúng tôi</li>
        </ul>
      </ul>
      <h3>V. QUYỀN LỰA CHỌN VÀ QUYỀN CỦA BẠN</h3>
      <p><b>Vị trí ứng dụng.</b>  Như đã giải thích chi tiết hơn trong phần Thông tin chúng tôi thu thập và sử dụng ở trên, chúng tôi thu thập thông tin về vị trí của bạn nếu bạn bật dịch vụ vị trí thông qua cài đặt trong thiết bị di động của mình hoặc với sự đồng ý của bạn, tùy theo yêu cầu của luật pháp. Bạn có thể thay đổi cài đặt quyền riêng tư của thiết bị bất kỳ lúc nào để tắt việc chia sẻ thông tin vị trí này với Dịch vụ của chúng tôi. Nếu bạn chọn tắt dịch vụ vị trí, điều này có thể ảnh hưởng đến một số tính năng nhất định của Dịch vụ của chúng tôi. Nếu bạn có câu hỏi cụ thể về cài đặt quyền riêng tư của thiết bị, chúng tôi khuyên bạn nên liên hệ với nhà sản xuất thiết bị hoặc nhà cung cấp dịch vụ di động của mình để được trợ giúp.</p>
      <p><b>Kiểm soát thông tin trong tài khoản của bạn.</b> Nếu bạn đã tạo tài khoản trực tuyến với chúng tôi và muốn cập nhật thông tin bạn đã cung cấp cho chúng tôi, bạn có thể truy cập tài khoản của mình để xem và cập nhật thông tin của bạn. Bạn cũng có thể liên hệ với chúng tôi như mô tả trong  phần Cách liên hệ với chúng tôi bên dưới.</p>
      <p><b>Các Quyền Riêng Tư Hợp Pháp Khác.</b> Ngoài bất kỳ quyền nào được nêu trong Điều khoản sử dụng, và/hoặc khi áp dụng theo luật tại Việt Nam, bạn hoặc người dùng nhà hàng của bạn có thể có các quyền sau liên quan đến thông tin cá nhân của bạn:</p>
      <ul>
        <li>Quyền truy cập thông tin cá nhân mà chúng tôi nắm giữ về bạn</li>
        <li>Quyền được sửa hoặc cập nhật thông tin cá nhân của bạn</li>
        <li>Quyền yêu cầu xóa thông tin cá nhân của bạn</li>
        <li>Quyền hạn chế cách chúng tôi xử lý thông tin cá nhân của bạn</li>
        <li>Quyền phản đối cách chúng tôi sử dụng thông tin cá nhân của bạn nếu cơ sở pháp lý để xử lý thông tin đó là lợi ích hợp pháp của chúng tôi.</li>
      </ul>
      <p>Khi chúng tôi sử dụng thông tin cá nhân của bạn dựa trên sự đồng ý của bạn và khi áp dụng theo luật địa phương, bạn có quyền rút lại sự đồng ý đó bất kỳ lúc nào. Khi bạn đã đồng ý nhận thông tin tiếp thị trực tiếp từ chúng tôi và khi áp dụng theo luật tại Việt Nam, bạn có thể rút lại sự đồng ý đó bất kỳ lúc nào.</p>
      <p>Nếu bạn hoặc người dùng nhà hàng của bạn muốn thực hiện các quyền hợp pháp mà bạn có thể có theo luật Việt Nam hiện hành, vui lòng gửi yêu cầu của bạn đến contact@dinnerchill.vn. Để chúng tôi có thể xử lý yêu cầu của bạn tốt hơn, vui lòng cung cấp email bạn sử dụng để đăng nhập vào tài khoản Dinner Chill của bạn. Nếu bạn không có tài khoản Dinner Chill, vui lòng cung cấp email và bất kỳ thông tin liên hệ có liên quan nào khác mà bạn đã sử dụng để thực hiện yêu cầu hoặc sử dụng Dịch vụ của chúng tôi.</p>
      <h3>VI. CHUYỂN GIAO THÔNG TIN QUỐC TẾ</h3>
      <p>Chúng tôi có thể hợp tác với các nền tảng khác (bên thứ ba, như Google Map) để cung cấp Dịch vụ cho bạn vì thế thông tin về bạn hoặc người dùng nhà hàng của bạn sẽ được chuyển đến hoặc được truy cập bởi các thực thể đó, trên toàn thế giới như được mô tả trong Chính sách này. Một số thực thể này có thể nằm ở các quốc gia khác, không cung cấp mức độ bảo vệ thông tin cá nhân tương đương với quốc gia của bạn (Việt Nam).</p>
      <p>Chúng tôi đã đưa ra các biện pháp bảo vệ được thiết kế để cung cấp sự bảo vệ đầy đủ cho việc chuyển giao một số thông tin nhất định, theo các yêu cầu pháp lý hiện hành. Để biết thêm thông tin về các biện pháp bảo vệ phù hợp đã được áp dụng hoặc để yêu cầu một bản sao của các biện pháp bảo vệ này, vui lòng liên hệ với chúng tôi bằng thông tin liên hệ được liệt kê trong phần Cách liên hệ với chúng tôi bên dưới.</p>
      <h3>VII. LIÊN KẾT ĐẾN CÁC TRANG WEB KHÁC</h3>
      <p>Dịch vụ của chúng tôi chứa các liên kết đến các trang web hoặc dịch vụ khác không thuộc sở hữu hoặc kiểm soát của Dinner Chill, bao gồm các liên kết đến các trang web của nhà hàng và các chi nhánh nhà hàng và các nhà quảng cáo của chúng tôi, hay các đối tác kinh doanh khác. Chính sách này chỉ áp dụng cho thông tin được thu thập bởi Dịch vụ của chúng tôi. Chúng tôi không kiểm soát các trang web của bên thứ ba này và việc bạn sử dụng các trang web và tính năng của bên thứ ba phải tuân theo các chính sách bảo mật được đăng trên các trang web đó. Chúng tôi không chịu trách nhiệm hoặc nghĩa vụ pháp lý đối với quyền riêng tư hoặc hoạt động kinh doanh của bất kỳ trang web của bên thứ ba nào được liên kết với Dịch vụ của chúng tôi. Việc bạn sử dụng các trang web của bên thứ ba được liên kết với Dịch vụ của chúng tôi là do bạn tự chịu rủi ro, vì vậy chúng tôi khuyến khích bạn đọc chính sách bảo mật của bất kỳ trang web của bên thứ ba nào được liên kết khi bạn rời khỏi một trong các Dịch vụ của chúng tôi.</p>
      <h3>VIII. VỚI TRẺ EM</h3>
      <p>Dịch vụ của chúng tôi không hướng đến hoặc dành cho trẻ em dưới độ tuổi trưởng thành sử dụng tại các khu vực pháp lý áp dụng. Chúng tôi không cố ý thu thập thông tin từ trẻ em dưới 16 tuổi. Nếu bạn biết rằng một cá nhân dưới 16 tuổi đã cung cấp thông tin cho chúng tôi mà không có sự đồng ý của bạn, vui lòng liên hệ với chúng tôi theo thông tin liên hệ được liệt kê trong phần Cách liên hệ với chúng tôi bên dưới.</p>
      <h3>IX. THAY ĐỔI CHÍNH SÁCH NÀY</h3>
      <p>Ngoại trừ phạm vi giới hạn theo luật hiện hành, chúng tôi sẽ cập nhật Chính sách này theo thời gian để phản ánh những thay đổi trong các hoạt động bảo mật, yêu cầu pháp lý và các yếu tố khác của chúng tôi bằng cách đăng thông báo cập nhật một cách nổi bật trên Dịch vụ của chúng tôi. Những thay đổi đối với Chính sách của chúng tôi sẽ có hiệu lực khi được đăng và ngày có hiệu lực mới sẽ được xác định.</p>
      <p>Nếu chúng tôi thực hiện bất kỳ thay đổi nào đối với Chính sách có tác động đáng kể đến thông tin cá nhân đã thu thập trước đó về bạn, chúng tôi sẽ nỗ lực hợp lý để thông báo và xin sự đồng ý đối với bất kỳ thay đổi nào theo yêu cầu của pháp luật.</p>
      <h3>X. CÁCH LIÊN HỆ VỚI CHÚNG TÔI</h3>
      <p>Nếu bạn có bất kỳ câu hỏi nào về Chính sách này hoặc cách thông tin cá nhân của bạn được sử dụng, vui lòng liên hệ với chúng tôi qua email tại <b>contact@dinnerchill.vn</b> hoặc qua thư bưu chính tại:</p>
      <ul>
        <li>Công ty Cổ phần Dinner Chill</li>
        <li>Địa chỉ: Tầng 9, Tòa Dinner Chill, Số 123 Đường Ẩm Thực, Quận Ẩm Thực, Thành phố Hà Nội, Việt Nam</li>
        <li>Số điện thoại: 1900 9999</li>
        <li>Email: contact@dinnerchill.vn</li>
      </ul>
      <p>Chân thành cảm ơn và chúc Quý Khách trải nghiệm Dinner Chill hài lòng, vui vẻ!</p>
    </div>
  </div>
);

export default PrivacyPolicy; 